version: "3"

services:
  chzuService:
    image: chzu-boot:1.0
    container_name: chzu-boot
    ports:
      - "8080:8080"
    volumes:
      - /app/chzuService:/data
    networks:
      - chzu_net
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:6.0.8
    ports:
      - "6379:6379"
    volumes:
      - /app/redis/redis-conf:/etc/redis/redis-conf
      - /app/redis/data:/data
    networks:
      - chzu_net
    command:
      - redis-server
      - /etc/redis/redis-conf

  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'chzu'
      MYSQL_USER: 'chzu'
      MYSQL_PASSWORD: 'chzu'
    ports:
      - "3306:3306"
    volumes:
      - /app/mysql/db:/var/lib/mysql
      - /app/mysql/mysql-conf:/etc/mysql-conf
      - /app/mysql/init:/docker-entrypoint-initdb
    networks:
      - chzu_net
    command:
      - --default-authentication-plugin=mysql_native_password #解决外部无法访问

networks:
  chzu_net: